export const GET_BOATS = 'GET_BOATS'
export const GET_BOAT_BY_NAME = 'GET_BOAT_BY_NAME'
export const GET_RATES = 'GET_RATES'
export const GET_POLICIES = 'GET_POLICIES'
export const GET_CONTACT = 'GET_CONTACT'

export const LOAD_BOATS_SUCCESS = 'LOAD_BOATS_SUCCESS'
export const LOAD_POLICIES_SUCCESS = 'LOAD_POLICIES_SUCCESS'
export const LOAD_RATES_SUCCESS = 'LOAD_RATES_SUCCESS'
